version: '3.1'

services:

  mongo:
    image: mongo:latest
    hostname: todo_mongo_db
    volumes:
      - ./data:/data/db

  todo-app:
    build: .
    depends_on:
      - mongo
    command: python -u app.py
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo